<a href="https://colab.research.google.com/github/dvt991/DeepLearningPyTorch/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensors

### Main discovered functions
Pytorch tensors are the main object to be used when programming using Pytorch library, they implement any scalar, vector, matrix (2D & 3D) as well as a set of functions which makes the life easier when operating them.
One of the main benefits of using Pytorch is ts ability for calculating gradients (parcial derivates) of the tensors. Which may be used for minimizing the error of a model using the gradient descent method.

After a review of the tensor documentation, find below my selected functions.  
- torch.random(): fills the tensor with random values
- torch.eig(): computes the eigenvectors of the tensor
- resize_(): resize the tensor to a given size
- select(): slices the tensor along the selected dimension at the given index
- where(): returns a tensor with the values that met the conditon

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.random()

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)



In [0]:
# creating an tensor Matrix 3x3 using a random numbers from a normal distribution
t1 = torch.randn(3, 3)
t1

tensor([[-0.2895, -0.5728,  0.4338],
        [ 0.3157, -0.3295,  0.2898],
        [-0.0751, -0.1587,  0.0605]])

Created a tensor of dimension 2x2 (matrix)

In [0]:
# creating an tensor 3-D Matrix 2x3x2 using a random numbers from a normal distribution
t1_2 = torch.randn(2,3, 2)
t1_2

tensor([[[-0.5084, -0.4123],
         [ 0.8298, -0.3162],
         [ 0.4710, -0.2236]],

        [[-1.9246,  1.1891],
         [ 1.9553, -0.8070],
         [-1.1956,  0.6041]]])

Created a tensor of 3 dimensions filled with random values

In [0]:
# Example 3 - breaking (by using a non existent data type "torch.string")
t1_3 = torch.randn(2, 3, 2, dtype=torch.string, requires_grad=True )

AttributeError: ignored

Tried to initialize an tensor with random valus of torch type string, which obviously does not exists and therefore an attributeError is raised informing about the situation.

This function may be very useful when creating new tensor from scracth, for example as seen during the first lesson, for initializing the weights or the biases tensors.

## Function 2 - torch.eig()

Computes both eigenvectors and eigenvalues of the given tensor matrix. The given matrix shall be squared.

In [0]:
# Example 1 - obtained eigenvalues and vector of the matrix obtained in previous section
t2 = torch.tensor([[1., 1, 0],
                   [1, 0, 1],
                   [0, 1, 1]])
t2.dtype

torch.float32

Once obtained, the eigenvalues are accesible by using .eigenvalues

In [0]:
# Example 2 - working
t2 = torch.eig(t2, True)
print(t2.eigenvalues)
print(t2.eigenvectors)

tensor([[-1.0000,  0.0000],
        [ 1.0000,  0.0000],
        [ 2.0000,  0.0000]])
tensor([[ 4.0825e-01,  7.0711e-01,  5.7735e-01],
        [-8.1650e-01,  8.1591e-08,  5.7735e-01],
        [ 4.0825e-01, -7.0711e-01,  5.7735e-01]])


In [0]:
# Example 3 - breaking (to illustrate when it breaks)
t2_vectors_t = torch.t(t2.eigenvectors)
tensor_out = t2.eigenvectors @ t2.eigenvalues @ t2_vectors_t
tensor_out

RuntimeError: ignored

Explanation about example

Closing comments about when to use this function

## Function 3 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 4 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 5 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 2.5MB/s 


In [0]:
import jovian

In [0]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
