<a href="https://colab.research.google.com/github/dvt991/DeepLearningPyTorch/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Daniel Velasco Torre

# PyTorch Tensors

### Main discovered functions
Pytorch tensors are the main object to be used when programming using Pytorch library, they implement any scalar, vector, matrix (2D & 3D) as well as a set of functions which makes the life easier when operating them.
One of the main benefits of using Pytorch is ts ability for calculating gradients (parcial derivates) of the tensors. Which may be used for minimizing the error of a model using the gradient descent method.

After a review of the tensor documentation, find below my selected functions.  
- randn(): fills the tensor with random values
- view(): resizes the given tensor into  new one
- grad(): returns the gradient calculated by autograd
- select(): slices the tensor along the selected dimension at the given index
- where(): returns a tensor with the values that met the conditon

In [0]:
# Import torch and other required modules
import torch

## Function 1 - random()

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1.



In [2]:
# creating an tensor Matrix 3x3 using a random numbers from a normal distribution
t1 = torch.randn(3, 3)
t1

tensor([[ 0.3195,  1.5224,  1.3008],
        [ 0.9722,  0.9984,  1.0700],
        [ 0.6215, -0.2685,  0.4946]])

Created a tensor of dimension 2x2 (matrix)

In [3]:
# creating an tensor 3-D Matrix 2x3x2 using a random numbers from a normal distribution
t1_2 = torch.randn(2,3, 2)
t1_2

tensor([[[ 1.5359,  0.9600],
         [ 0.2890,  1.5561],
         [-1.9615, -0.1194]],

        [[-0.9531,  2.2391],
         [ 1.1436,  0.2132],
         [ 0.7284, -1.4723]]])

Created a tensor of 3 dimensions filled with random values

In [0]:
# Example 3 - breaking (by using a non existent data type "torch.string")
t1_3 = torch.randn(2, 3, 2, dtype=torch.string, requires_grad=True )

AttributeError: ignored

Tried to initialize an tensor with random valus of torch type string, which obviously does not exists and therefore an attributeError is raised informing about the situation.

This function may be very useful when creating new tensor from scracth, for example as seen during the first lesson, for initializing the weights or the biases tensors.


---



---



## Function 2 - view()

Returns a new tensor with the same data as the <code>self</code> tensor but of a different <code>shape</code>

In [7]:
# Example 1 - created an example of a 2x2 tensor and resize it to a single dimension
t2 = torch.randn(2,2)
print(t2.size())
t2_resized = t2.view(4)
t2_resized

torch.Size([2, 2])


tensor([-1.8875, -0.4700,  0.1409,  1.1345])

In [14]:
# Example 2 - created a 3-dimensional tensor with 2 3x3 matrices and resize it to 2 vectors of X length
# where the length in indicated as to be calculated by pytorch by using -1
t2_1 = torch.rand(2,3,3)
print(t2_1)
t2_1_resized = t2_1.view(2, 1 , -1)
print(t2_1_resized)

tensor([[[0.0694, 0.8559, 0.8598],
         [0.6338, 0.6708, 0.1369],
         [0.4764, 0.0014, 0.5037]],

        [[0.3369, 0.2449, 0.8158],
         [0.8555, 0.5010, 0.7545],
         [0.2088, 0.5222, 0.7234]]])
tensor([[[0.0694, 0.8559, 0.8598, 0.6338, 0.6708, 0.1369, 0.4764, 0.0014,
          0.5037]],

        [[0.3369, 0.2449, 0.8158, 0.8555, 0.5010, 0.7545, 0.2088, 0.5222,
          0.7234]]])


The view method shown above shall be very useful for managing the dimension resizing between NN layers.

In [18]:
# Example 3 - another example where is shown how the function resturns an error if the dimension
#does not meet the requirements
t2_2 = torch.randn(2,2,2)
print(t2_2)
t2_2_resized = t2_2.view(1, 3, -1)
print(t2_2_resized)

tensor([[[-0.3005, -0.7203],
         [-1.2149,  0.7053]],

        [[ 0.6251, -1.1613],
         [-0.0663, -0.9618]]])


RuntimeError: ignored

The previous example returns an error because our input is a 3-Dimensional tensor containing 2x2x2=8 elements. When resized, we are giving as arguments the first dimension and second simension in which it shall be reshaped (1x3x**n**).   
And it can be easily seen, that there is no number **n**, which meet that 1x3x**n**=8
When used properly, view is a must-known method among the tensor library.



---



---





## Function 3 - grad()

Method which returns the stored value f the calculation made over a tensor by the automatic differentiation system of pytorch (autograd). The values are being added until they are manually cleaned. It may be used together with requires_grad() which sets the autograf on and off to a specific tensor.


In [23]:
# Example 1 - First tensor requirining autograd without backward propagation
torch_ag = torch.randn(3,2, requires_grad=True)
print(torch_ag)
out_ag = torch_ag *3
print(out_ag)
print(torch_ag.grad)


tensor([[-2.2276,  0.3772],
        [ 1.6913,  1.8568],
        [-0.8133,  0.3853]], requires_grad=True)
tensor([[-6.6828,  1.1316],
        [ 5.0740,  5.5705],
        [-2.4400,  1.1558]], grad_fn=<MulBackward0>)
None


In the example above a random 3x2 tensor is created from which autograd will be recording all its operations from the moment is created.
Then it is multiplied by a scalar 2.
But when the gradient is then requested None is obtained, this is because the backpropagatton has not been carried out.

In [25]:
# Example 2 - Grad used together with backwards
torch_ag_2 = torch.randn(3,3, requires_grad=True)
print(torch_ag_2)
out_ag = torch_ag.pow(2).sum()
print(out_ag)
out_ag.backward()
print(torch_ag.grad)

tensor([[ 0.3211, -0.4570,  1.2109],
        [ 0.7785,  0.2847, -0.1551],
        [ 0.3697,  0.4899,  1.3948]], requires_grad=True)
tensor(12.2229, grad_fn=<SumBackward0>)
tensor([[-3.4552,  1.7544],
        [ 4.3827,  4.7137],
        [-0.6267,  1.7706]])


Now when the derivates are being calculated using the chain rules backwards, the the grad() value can be accessed.

In [26]:
# Example 3 - Using grad() we can break it if we do not reset the grad tensor to zero
#because the gradients are being added.Lets see an example
torch_ag_3 = torch.randn(3,3, requires_grad=True)
print(torch_ag_3)
out_ag = torch_ag.pow(2).sum()
print(out_ag)
out_ag.backward()
print("First dy/dx :", torch_ag.grad)
#we do not reset gradients
out_ag_1 = torch_ag.pow(2).sum()
print(out_ag_1)
out_ag_1.backward()
print("Second dy/dx :", torch_ag.grad)

tensor([[ 0.2895, -0.2748,  1.6189],
        [-0.0550, -0.8474, -1.2440],
        [-2.0512,  0.4041, -0.7822]], requires_grad=True)
tensor(12.2229, grad_fn=<SumBackward0>)
First dy/dx : tensor([[-7.9105,  2.5088],
        [ 7.7653,  8.4273],
        [-2.2534,  2.5411]])
tensor(12.2229, grad_fn=<SumBackward0>)
Second dy/dx : tensor([[-12.3657,   3.2632],
        [ 11.1480,  12.1410],
        [ -3.8800,   3.3117]])


It can be seen that even tough the calculation is the same for both situation starting from the same tensor values, the result of the grad is different! this is because the gradients related to a tensor shall be manually reset.

In [27]:
#example where the gradients are reset
torch_ag_4 = torch.randn(3,3, requires_grad=True)
print(torch_ag_4)
out_ag_4 = torch_ag_4.pow(2).sum()
print(out_ag_4)
out_ag_4.backward()
print("First dy/dx :", torch_ag_4.grad)
#we do reset gradients
torch_ag_4.grad.zero_()

out_ag_5 = torch_ag_4.pow(2).sum()
print(out_ag_5)
out_ag_5.backward()
print("Second dy/dx :", torch_ag_4.grad)

tensor([[ 1.1674, -0.2521, -0.3498],
        [-0.1106,  0.7092,  0.7290],
        [-1.3655, -0.2924, -0.0019]], requires_grad=True)
tensor(4.5453, grad_fn=<SumBackward0>)
First dy/dx : tensor([[ 2.3349, -0.5042, -0.6996],
        [-0.2212,  1.4183,  1.4579],
        [-2.7309, -0.5847, -0.0039]])
tensor(4.5453, grad_fn=<SumBackward0>)
Second dy/dx : tensor([[ 2.3349, -0.5042, -0.6996],
        [-0.2212,  1.4183,  1.4579],
        [-2.7309, -0.5847, -0.0039]])


We saw during this example the whole functionality of the autograd in one tensor.


---



---



## Function 4 - select()

Slices the self tensor along the selected dimension at the given index. This function returns a view of the original tensor with the given dimension removed.

In [33]:
# Example 1 - First approach to the funtion in a 2-Dimension tensor
t4 = torch.randn(3,4)
print(t4)
#selected the first dimension (row) and 2 index (2º row)
t4.select(0,1)


tensor([[ 0.6004,  0.3728,  0.7584,  0.9755],
        [ 0.1234, -1.2345,  1.2973,  0.2076],
        [ 0.0936, -1.4467,  0.0548,  0.0816]])


tensor([ 0.1234, -1.2345,  1.2973,  0.2076])

In the example above we selected a sub-tensor from a tensor. given the dimension and index to be extracted.
Now we try with higher dimensional tensors and we will try to understand how to use it under such circunstances.

In [37]:
# Example 2 - Selectinh higher dimensional arrays
# for example 2 sets of 3 2x2 matrices
t4_1 = torch.randn(2,3,2,2)
print(t4_1)
t4_1.select(0, 1)

tensor([[[[-0.0200, -1.7871],
          [ 0.8136,  0.3182]],

         [[ 0.1033,  0.8886],
          [ 2.2203,  0.1874]],

         [[-0.3291, -0.5627],
          [ 0.7899,  0.1892]]],


        [[[ 1.1983, -0.2934],
          [-0.4307,  0.2958]],

         [[-1.4634, -0.2771],
          [-0.2457, -0.0633]],

         [[ 0.1074, -0.5297],
          [ 0.3714,  1.5535]]]])


tensor([[[ 1.1983, -0.2934],
         [-0.4307,  0.2958]],

        [[-1.4634, -0.2771],
         [-0.2457, -0.0633]],

        [[ 0.1074, -0.5297],
         [ 0.3714,  1.5535]]])

It can be seen in the example above, that we are selecting the first dimension (0) which correspond to the sets, and from them the second set (1).
Note that the indexes starts at 0.

In [38]:
# Example 3 - Breaking the method by selecting a higher dimension than the ones from the tensor
t4_2 = torch.randn(3,4,5,6)
print(t4_2.size())
t4_2.select(1,4)

torch.Size([3, 4, 5, 6])


IndexError: ignored

In the example above the errors comes from selecting an index 4 in dimension 1 where the maximum (starting in 0) would be 3 (dimension = 4).

Very interesting function for selecting subset of data from a given tensor. For example i can imagine it can be used when a tensor 3x128x128 represents 3 channels of a RGB image. Select() then, may be used for selecting each of the channels to its own tensor.

---



## Function 5 - where()

Return a tensor of elements selected from either x or y, depending on condition.


In [54]:
# Example 1 - first approach to the funtion
t5 = torch.zeros(3,3)
print(t5)
#last row set to ones
t5[2,:] = torch.ones(1,3)
print(t5)
#where applied
t5_out = torch.where(t5<0.5, torch.tensor(0.1), torch.tensor(0.9)) 
t5_out

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]])


tensor([[0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000],
        [0.9000, 0.9000, 0.9000]])

The example above shows how where() can be used for modifying values of a tensor under certain circunstances 

In [56]:
# Example 2 - where() used for gettng values from another tensor
# the negative values from t5_1 are modified by the values in t5_2 (all of them 1's)
t5_1 = torch.randn(3, 3)
t5_2 = torch.ones(3, 3)
print(t5_1)
torch.where(t5_1 > 0, t5_1, t5_2)

tensor([[-0.9704,  0.9675, -0.9089],
        [ 0.6830, -0.5334,  0.5500],
        [ 1.2057, -0.2569,  0.3177]])


tensor([[1.0000, 0.9675, 1.0000],
        [0.6830, 1.0000, 0.5500],
        [1.2057, 1.0000, 0.3177]])

Finally, below we will show can the where method may be misused by for example setting a non boolean expression

In [57]:
# Example 3 - breaking it by a non-boolean expresion
t5_1 = torch.randn(3, 3)
print(t5_1)
torch.where(t5_1 = 0, t5_1, torch.tensor(1))

SyntaxError: ignored

It can be seen, that the expression <code> t5_1= 0 </code> which is not a boolean expression crashes the method with a SyntaxError.

Where() function is quite interesting, in order for example to fill missing or wrong values in a large tensor based on a condition (as seen above, for example removing all negative values of the tensor)

## Conclusion

In this notebook, a set of very useful and common method related to the Tensor objects of Pytorch has been explained. Special attention may be payed to the grad() and view() method which will be extensively used when programing using Pytorch library.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [58]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 2.7MB/s 


In [0]:
import jovian

In [60]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
